import type { TimelineEvent } from "@/lib/types";

export const BITCOIN_TIMELINE: TimelineEvent[] = [
  {
    id: "2008-wp",
    date: "2008-10-31",
    titlePt: "Whitepaper",
    titleEn: "Whitepaper",
    bodyPt: "Satoshi Nakamoto publica «Bitcoin: A Peer-to-Peer Electronic Cash System».",
    bodyEn: "Satoshi Nakamoto publishes “Bitcoin: A Peer-to-Peer Electronic Cash System”.",
    importance: "high",
  },
  {
    id: "2009-genesis",
    date: "2009-01-03",
    titlePt: "Bloco génese",
    titleEn: "Genesis block",
    bodyPt: "Primeiro bloco minerado. Mensagem: bailouts bancários no Times.",
    bodyEn: "First block mined. Message references bank bailouts in The Times.",
    importance: "high",
    priceHint: "~$0",
  },
  {
    id: "2010-pizza",
    date: "2010-05-22",
    titlePt: "Bitcoin Pizza Day",
    titleEn: "Bitcoin Pizza Day",
    bodyPt: "10 000 BTC por duas pizzas — primeira compra comercial famosa.",
    bodyEn: "10,000 BTC for two pizzas — famous early commercial purchase.",
    importance: "medium",
  },
  {
    id: "2012-h1",
    date: "2012-11-28",
    titlePt: "1.º Halving",
    titleEn: "1st Halving",
    bodyPt: "Recompensa cai de 50 para 25 BTC.",
    bodyEn: "Block reward falls from 50 to 25 BTC.",
    importance: "high",
  },
  {
    id: "2013-ath",
    date: "2013-12-01",
    titlePt: "Bolha 2013",
    titleEn: "2013 bubble",
    bodyPt: "Preço supera $1 000 antes de um longo inverno.",
    bodyEn: "Price tops $1,000 before a long winter.",
    importance: "medium",
    priceHint: "~$1,000",
  },
  {
    id: "2016-h2",
    date: "2016-07-09",
    titlePt: "2.º Halving",
    titleEn: "2nd Halving",
    bodyPt: "Recompensa para 12,5 BTC.",
    bodyEn: "Reward to 12.5 BTC.",
    importance: "high",
  },
  {
    id: "2017-ath",
    date: "2017-12-17",
    titlePt: "Euforia 2017",
    titleEn: "2017 euphoria",
    bodyPt: "Quase $20 000. ICO mania. Lição: narrativas escalam mais depressa que literacia.",
    bodyEn: "Near $20,000. ICO mania. Lesson: narratives scale faster than literacy.",
    importance: "high",
    priceHint: "~$20k",
  },
  {
    id: "2020-h3",
    date: "2020-05-11",
    titlePt: "3.º Halving",
    titleEn: "3rd Halving",
    bodyPt: "Recompensa para 6,25 BTC. Narrativa «digital gold» institucional.",
    bodyEn: "Reward to 6.25 BTC. Institutional “digital gold” narrative.",
    importance: "high",
  },
  {
    id: "2021-ath",
    date: "2021-11-10",
    titlePt: "ATH 2021",
    titleEn: "2021 ATH",
    bodyPt: "Ciclo com ETFs futures, El Salvador e euforia retail.",
    bodyEn: "Cycle with futures ETFs, El Salvador and retail euphoria.",
    importance: "high",
    priceHint: "~$69k",
  },
  {
    id: "2022-ftx",
    date: "2022-11-11",
    titlePt: "Colapso FTX",
    titleEn: "FTX collapse",
    bodyPt: "Risco de custódia e contraparte em destaque mundial.",
    bodyEn: "Custody and counterparty risk in the global spotlight.",
    importance: "high",
  },
  {
    id: "2024-etf",
    date: "2024-01-10",
    titlePt: "ETFs spot EUA",
    titleEn: "US spot ETFs",
    bodyPt: "Aprovação dos ETFs spot de BTC — canal institucional massivo.",
    bodyEn: "US spot BTC ETFs approved — massive institutional channel.",
    importance: "high",
  },
  {
    id: "2024-h4",
    date: "2024-04-20",
    titlePt: "4.º Halving",
    titleEn: "4th Halving",
    bodyPt: "Recompensa para 3,125 BTC. Ciclo actual em curso.",
    bodyEn: "Reward to 3.125 BTC. Current cycle underway.",
    importance: "high",
  },
  {
    id: "2024-mica",
    date: "2024-12-30",
    titlePt: "MiCA CASP pleno",
    titleEn: "Full MiCA CASP",
    bodyPt: "Regime MiCA para prestadores de serviços na UE — relevante para Portugal.",
    bodyEn: "MiCA regime for crypto-asset service providers in the EU — relevant for Portugal.",
    importance: "high",
  },
];
